server:
  port: 0
spring:
  application:
    name: productcomposite
eureka:
  instance:
    leaseExpirationDurationInSeconds: 5
    leaseRenewalIntervalInSeconds: 3
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${random.value}}}
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.xstream: INFO
