server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  instance:
    leaseExpirationDurationInSeconds: 5
    leaseRenewalIntervalInSeconds: 3
  client:
    registerWithEureka: false
    fetchRegistry: false

  server:
      waitTimeInMsWhenSyncEmpty: 0

